#ifndef XPLAY_COMMON_H
#define XPLAY_COMMON_H

#define XPLAY_OPEN_NOT_OPENED				0	// this will be never returned from OpenFile
#define XPLAY_OPEN_OK						1
#define XPLAY_OPEN_ERROR_UNSUPPORTED_FILE_FORMAT 2
#define XPLAY_OPEN_ERROR_SNDFILE			3
#define XPLAY_OPEN_ERROR_SNDFILE_NOT_WAV	4
#define XPLAY_OPEN_ERROR_NOMEM_FOR_BUFFER	5
#define XPLAY_OPEN_ERROR_MPG123_INIT		6
#define XPLAY_OPEN_ERROR_MPG123_OPEN		7
#define XPLAY_OPEN_ERROR_MPG123_UNSUPPORTED_ENC	8

#endif
